version: '3.1'

services:
  books-finder:
    image: bkf:1
    restart: always
    depends_on:
      - mongodb
    ports:
      - 1999:80

  mongodb:
     image: mongo
     restart: always
     ports:
       - 27018:27017
     environment:
       MONGO_INITDB_ROOT_USERNAME: root
       MONGO_INITDB_ROOT_PASSWORD: password

  mongo-express:
     image: mongo-express
     restart: always
     depends_on:
       - mongodb
     ports:
       - 8072:8081
     environment:
       ME_CONFIG_MONGODB_ADMINUSERNAME: root
       ME_CONFIG_MONGODB_ADMINPASSWORD: password
       ME_CONFIG_MONGODB_SERVER: mongodb